Restore Develocity Build Scan integration (#1505)
* Add IP compatibility test

* Add IP-incompatible Develocity integration

Makes IP compatibility test fail.

* Fix IP compatibility

Fix by accessing the "buildScan" extension that's available since Develocity Gradle plugin 4.0.

* Fix IP compatibility if using older Develocity plugin

* Use recommended artifact coordinates

* Cleanups

* Fix condition and Task configuration

* Fix runtime usage of Develocity classes

Move usage out of the plugin into a separate class/file. Since
the plugin is a compileOnly dependency, it must only be referenced
if the plugin/extension is present at runtime, which includes imports.

```
org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin class 'com.github.jengelman.gradle.plugins.shadow.ShadowPlugin'.
> org.gradle.api.plugins.PluginInstantiationException: Could not create plugin of type 'ShadowPlugin'.
   > org.gradle.internal.instantiation.ClassGenerationException: Could not generate a decorated class for type ShadowPlugin.
      > java.lang.NoClassDefFoundError: com/gradle/develocity/agent/gradle/scan/BuildScanConfiguration
         > java.lang.ClassNotFoundException: com.gradle.develocity.agent.gradle.scan.BuildScanConfiguration
```

Issue caught by functional tests: https://scans.gradle.com/s/k2zkknzaf3ex4

* Fix spotless violation

* Update legacy ABI

* Remove 2nd extension lookup

* Refactor integration

* Add didWork custom value

* Avoid publishing Scan during test

* Cleanups

* Use `findOptionalProperty`

* Move and rename

---------

Co-authored-by: Goooler <wangzongler@gmail.com>